//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activation
    {
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string day { get; set; }
        public string HMG { get; set; }
        public string FSH { get; set; }
        public string RT1 { get; set; }
        public string RT2 { get; set; }
        public string RT3 { get; set; }
        public string RT4 { get; set; }
        public string LT1 { get; set; }
        public string LT2 { get; set; }
        public string LT3 { get; set; }
        public string LT4 { get; set; }
        public string End_thickness { get; set; }
        public string End_pattern { get; set; }
        public string E2 { get; set; }
    }
}
