//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class add_list
    {
        public int id { get; set; }
        public Nullable<int> add_id { get; set; }
        public string add_name { get; set; }
        public Nullable<double> add_value { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
