//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_balance
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
        public Nullable<double> in_val { get; set; }
        public Nullable<double> out_val { get; set; }
        public Nullable<int> inc_id { get; set; }
        public Nullable<int> pay_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string bank_name { get; set; }
    }
}
