//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_reception
    {
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string doctor_name { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> datenow { get; set; }
        public string type { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> check_out { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> ticketId { get; set; }
        public string Diagnosis { get; set; }
        public string Complaint { get; set; }
        public string note { get; set; }
        public Nullable<bool> printFlag { get; set; }
        public Nullable<bool> UUTS { get; set; }
        public Nullable<bool> LUTS { get; set; }
        public Nullable<bool> ED { get; set; }
        public Nullable<bool> Emergency { get; set; }
        public Nullable<bool> others { get; set; }
        public Nullable<bool> cong { get; set; }
        public Nullable<bool> post_mi { get; set; }
        public Nullable<bool> voidus { get; set; }
    }
}
