//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cong_Anthio
    {
        public int id { get; set; }
        public Nullable<bool> UUT { get; set; }
        public Nullable<bool> LUT { get; set; }
        public Nullable<bool> Hypospodias { get; set; }
        public Nullable<bool> Epispadias { get; set; }
        public Nullable<bool> undescTesties { get; set; }
        public string others { get; set; }
        public Nullable<int> pat_id { get; set; }
        public string pat_name { get; set; }
        public Nullable<int> Rec_id { get; set; }
    }
}
