//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepStock
    {
        public int id { get; set; }
        public Nullable<int> depid { get; set; }
        public string dep_name { get; set; }
        public Nullable<int> prod_id { get; set; }
        public string prod_name { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
