//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_history
    {
        public int id { get; set; }
        public Nullable<int> surgery_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public string device_name { get; set; }
        public Nullable<double> price { get; set; }
    }
}
