//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_account
    {
        public int id { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string doc_name { get; set; }
        public Nullable<double> in_val { get; set; }
        public Nullable<double> out_val { get; set; }
        public string title { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_name { get; set; }
        public string type { get; set; }
        public Nullable<int> p_historyID { get; set; }
    }
}
