//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_services
    {
        public int id { get; set; }
        public Nullable<int> serviceId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public Nullable<double> pricce { get; set; }
    }
}
