//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emagercy
    {
        public int id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public string pat_name { get; set; }
        public Nullable<bool> Ret { get; set; }
        public Nullable<bool> anuria { get; set; }
        public Nullable<bool> uiy_Hydronc { get; set; }
        public Nullable<bool> Ueeuia { get; set; }
        public Nullable<bool> pria_pism { get; set; }
        public Nullable<bool> Torsion { get; set; }
        public Nullable<bool> Gaugleue { get; set; }
        public Nullable<bool> inFlection { get; set; }
        public Nullable<bool> Trauua { get; set; }
        public string other { get; set; }
        public Nullable<int> Rec_id { get; set; }
    }
}
