//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exammination
    {
        public int id { get; set; }
        public string General { get; set; }
        public string Kiduey { get; set; }
        public string uerter { get; set; }
        public string Blodder { get; set; }
        public string oeuis { get; set; }
        public string Ureqra { get; set; }
        public string peruerum { get; set; }
        public string scrotcum { get; set; }
        public string uretiva { get; set; }
        public string P_R { get; set; }
        public string prostate { get; set; }
        public Nullable<int> pat_id { get; set; }
        public string pat_name { get; set; }
        public Nullable<int> Rec_id { get; set; }
    }
}
