//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_history
    {
        public int id { get; set; }
        public Nullable<int> patientId { get; set; }
        public string patient_name { get; set; }
        public Nullable<bool> Diabets { get; set; }
        public Nullable<bool> Hypiteusini { get; set; }
        public Nullable<bool> coucel { get; set; }
        public Nullable<bool> coucer_prostat { get; set; }
        public Nullable<bool> statues { get; set; }
        public Nullable<bool> Medical_equal_diseases { get; set; }
        public string other { get; set; }
    }
}
