//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finger
    {
        public int id { get; set; }
        public string photoNo { get; set; }
        public string enrollNo { get; set; }
        public string verifyMode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<double> hourNum { get; set; }
        public Nullable<double> shortmin { get; set; }
        public Nullable<double> extramin { get; set; }
        public Nullable<double> shorth { get; set; }
        public Nullable<double> extrah { get; set; }
    }
}
