//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frozen_embryo
    {
        public int id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public string d5 { get; set; }
        public string d6 { get; set; }
        public string d7 { get; set; }
        public string d8 { get; set; }
        public string d9 { get; set; }
        public string d10 { get; set; }
        public string d11 { get; set; }
        public string d12 { get; set; }
        public string d13 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
        public string d16 { get; set; }
        public string d17 { get; set; }
        public string d18 { get; set; }
        public string d19 { get; set; }
        public string d20 { get; set; }
        public string d21 { get; set; }
        public string d22 { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
        public string date3 { get; set; }
        public string es1 { get; set; }
        public string es2 { get; set; }
        public string es3 { get; set; }
        public string en1 { get; set; }
        public string en2 { get; set; }
        public string en3 { get; set; }
        public string in1 { get; set; }
        public string in2 { get; set; }
        public string in3 { get; set; }
        public string preg { get; set; }
        public string preg_date { get; set; }
        public string comment { get; set; }
    }
}
