//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hystroscopy
    {
        public int id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<int> Patserv_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string clinic_diag { get; set; }
        public string uterin_sounding { get; set; }
        public string intro { get; set; }
        public string uterin_cavity { get; set; }
        public string endometrium { get; set; }
        public string tubal { get; set; }
        public string distention { get; set; }
        public string diag { get; set; }
        public string paln { get; set; }
        public string operative_notes { get; set; }
    }
}
