//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icsi_report
    {
        public int id { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string protocol { get; set; }
        public string drugs { get; set; }
        public string period { get; set; }
        public string comment { get; set; }
        public string hcg { get; set; }
        public string coc { get; set; }
        public string pr { get; set; }
        public string np { get; set; }
        public string immotile { get; set; }
        public string ovm { get; set; }
        public string coc2 { get; set; }
        public string m2 { get; set; }
        public string m1 { get; set; }
        public string gv { get; set; }
        public string ez { get; set; }
        public string injected { get; set; }
        public string embryoT { get; set; }
        public string embryoS { get; set; }
    }
}
