//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inject
    {
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string proced { get; set; }
        public string protocol { get; set; }
        public string HMG_name { get; set; }
        public string FSH_name { get; set; }
        public string agonist { get; set; }
        public string antagonist { get; set; }
        public string semen_source { get; set; }
        public string Bmi { get; set; }
        public string Fsh { get; set; }
        public string LH { get; set; }
        public string PRL { get; set; }
        public string TSH { get; set; }
        public string AMH { get; set; }
        public string APHL { get; set; }
        public string ANA { get; set; }
        public string ATA { get; set; }
        public string Rubella { get; set; }
        public string HCV_HBV_AIDS { get; set; }
        public string ABO { get; set; }
        public string RH { get; set; }
        public string HB { get; set; }
        public string PC { get; set; }
        public string BT { get; set; }
        public string CT { get; set; }
        public string SGOT { get; set; }
        public string SGPT { get; set; }
        public string UREA { get; set; }
        public string CREATENIN { get; set; }
        public string hbv { get; set; }
        public string aids { get; set; }
    }
}
