//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUTS
    {
        public int id { get; set; }
        public Nullable<bool> Frequercy { get; set; }
        public Nullable<bool> No_Cuturia { get; set; }
        public Nullable<bool> Urgucy { get; set; }
        public Nullable<bool> Lu_contineuce { get; set; }
        public Nullable<bool> Stress { get; set; }
        public Nullable<bool> Lugluge { get; set; }
        public Nullable<bool> True { get; set; }
        public Nullable<int> pat_id { get; set; }
        public string pat_name { get; set; }
        public Nullable<int> rec_id { get; set; }
        public string txt { get; set; }
    }
}
