//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EccoHospitalEntities : DbContext
    {
        public EccoHospitalEntities()
            : base("name=EccoHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc_save> Acc_save { get; set; }
        public virtual DbSet<activation> activation { get; set; }
        public virtual DbSet<add_list> add_list { get; set; }
        public virtual DbSet<addition> addition { get; set; }
        public virtual DbSet<bank> bank { get; set; }
        public virtual DbSet<bank_balance> bank_balance { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<clinic> clinic { get; set; }
        public virtual DbSet<clinic_reception> clinic_reception { get; set; }
        public virtual DbSet<clinic_time> clinic_time { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<DepStock> DepStock { get; set; }
        public virtual DbSet<destroy> destroy { get; set; }
        public virtual DbSet<doctor_account> doctor_account { get; set; }
        public virtual DbSet<finger> finger { get; set; }
        public virtual DbSet<frozen_embryo> frozen_embryo { get; set; }
        public virtual DbSet<hystroscopy> hystroscopy { get; set; }
        public virtual DbSet<icsi_report> icsi_report { get; set; }
        public virtual DbSet<image> image { get; set; }
        public virtual DbSet<import> import { get; set; }
        public virtual DbSet<import_items> import_items { get; set; }
        public virtual DbSet<inject> inject { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<invoice_items> invoice_items { get; set; }
        public virtual DbSet<lab_history> lab_history { get; set; }
        public virtual DbSet<labb> labb { get; set; }
        public virtual DbSet<laparoscopic> laparoscopic { get; set; }
        public virtual DbSet<loan> loan { get; set; }
        public virtual DbSet<loan_installment> loan_installment { get; set; }
        public virtual DbSet<medical_report> medical_report { get; set; }
        public virtual DbSet<medicin> medicin { get; set; }
        public virtual DbSet<month_days> month_days { get; set; }
        public virtual DbSet<monthdetails> monthdetails { get; set; }
        public virtual DbSet<oberative_sheetTB> oberative_sheetTB { get; set; }
        public virtual DbSet<patient_services> patient_services { get; set; }
        public virtual DbSet<payementList> payementList { get; set; }
        public virtual DbSet<rad> rad { get; set; }
        public virtual DbSet<rad_history> rad_history { get; set; }
        public virtual DbSet<Rel_patient> Rel_patient { get; set; }
        public virtual DbSet<return_items> return_items { get; set; }
        public virtual DbSet<return_items2> return_items2 { get; set; }
        public virtual DbSet<returninv> returninv { get; set; }
        public virtual DbSet<returninv2> returninv2 { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<room_history> room_history { get; set; }
        public virtual DbSet<sanc_list> sanc_list { get; set; }
        public virtual DbSet<sanctions> sanctions { get; set; }
        public virtual DbSet<savee> savee { get; set; }
        public virtual DbSet<session_med> session_med { get; set; }
        public virtual DbSet<stadd> stadd { get; set; }
        public virtual DbSet<stadd_items> stadd_items { get; set; }
        public virtual DbSet<stock_destroy> stock_destroy { get; set; }
        public virtual DbSet<stocks> stocks { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<ticket_out> ticket_out { get; set; }
        public virtual DbSet<transfer> transfer { get; set; }
        public virtual DbSet<treat> treat { get; set; }
        public virtual DbSet<treatment> treatment { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<cong_Anthio> cong_Anthio { get; set; }
        public virtual DbSet<ED> ED { get; set; }
        public virtual DbSet<Emagercy> Emagercy { get; set; }
        public virtual DbSet<Family_history> Family_history { get; set; }
        public virtual DbSet<LUTS> LUTS { get; set; }
        public virtual DbSet<others> others { get; set; }
        public virtual DbSet<past_History> past_History { get; set; }
        public virtual DbSet<post_micturation> post_micturation { get; set; }
        public virtual DbSet<Stream_options> Stream_options { get; set; }
        public virtual DbSet<UTS> UTS { get; set; }
        public virtual DbSet<Voidues> Voidues { get; set; }
        public virtual DbSet<patient_history> patient_history { get; set; }
        public virtual DbSet<doctor_services> doctor_services { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<Exammination> Exammination { get; set; }
        public virtual DbSet<surgery_doctors> surgery_doctors { get; set; }
        public virtual DbSet<out_report> out_report { get; set; }
        public virtual DbSet<Surgery_history> Surgery_history { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<device_history> device_history { get; set; }
    }
}
