//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oberative_sheetTB
    {
        public int id { get; set; }
        public Nullable<int> patiant_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Expected_Total_number { get; set; }
        public string Collection { get; set; }
        public string media1 { get; set; }
        public string ICSI { get; set; }
        public string media2 { get; set; }
        public string EZ { get; set; }
        public string GV { get; set; }
        public string MI { get; set; }
        public string MII { get; set; }
        public string Quality { get; set; }
        public string Day2 { get; set; }
        public string Day3 { get; set; }
        public string Day4 { get; set; }
        public string Day5 { get; set; }
        public string DAy6 { get; set; }
        public string Date_transfer { get; set; }
        public string Number { get; set; }
        public string Grades { get; set; }
        public string Catheter { get; set; }
        public string Doctor_transfer { get; set; }
        public string Day_of_freez_embryo { get; set; }
        public string Tank_embryo { get; set; }
        public string canister_embryo { get; set; }
        public string code_embryo { get; set; }
        public string tube_embryo { get; set; }
        public string color_embryo { get; set; }
        public string media_embryo { get; set; }
        public string doctor_embryo { get; set; }
        public string notes_embryo { get; set; }
        public string Day_of_freez_analysis { get; set; }
        public string Tank_analysis { get; set; }
        public string canister_analysis { get; set; }
        public string code_analysis { get; set; }
        public string tube_analysis { get; set; }
        public string color_analysis { get; set; }
        public string media_analysis { get; set; }
        public string doctor_analysis { get; set; }
        public string notes_analysis { get; set; }
        public string out_come { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> del { get; set; }
    }
}
