//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class out_report
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_name { get; set; }
        public string Report_no { get; set; }
        public Nullable<System.DateTime> date_report { get; set; }
        public string medical_no { get; set; }
        public string arrival_type { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public string Medical_histoy { get; set; }
        public string physical_finding { get; set; }
        public string notes { get; set; }
        public string operation { get; set; }
        public Nullable<int> Rec_id { get; set; }
    }
}
