//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class past_History
    {
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<bool> smorokus { get; set; }
        public Nullable<bool> stones { get; set; }
        public Nullable<bool> operatient { get; set; }
        public Nullable<bool> Traunua { get; set; }
        public Nullable<bool> TB { get; set; }
        public Nullable<bool> Diabetes { get; set; }
        public Nullable<bool> Hypenteus { get; set; }
        public Nullable<bool> cancer { get; set; }
        public Nullable<bool> Ischluic_ttt { get; set; }
        public Nullable<bool> Astiua { get; set; }
        public Nullable<bool> candiac_Stuiet { get; set; }
        public string others { get; set; }
    }
}
