//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int id { get; set; }
        public string name { get; set; }
        public string age { get; set; }
        public string type { get; set; }
        public string nationalty { get; set; }
        public string phone { get; set; }
        public string Mobile { get; set; }
        public string government { get; set; }
        public string husband { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string social_state { get; set; }
        public string ssi { get; set; }
        public string job { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> enter_date { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string doc_name { get; set; }
        public string weight { get; set; }
        public string other { get; set; }
        public string code { get; set; }
        public string plus { get; set; }
        public string Temp { get; set; }
        public string Respiral { get; set; }
        public string BR2 { get; set; }
        public string BR1 { get; set; }
        public string Diabetes { get; set; }
        public string pregnancy { get; set; }
        public string hepatitis { get; set; }
        public string Asthma { get; set; }
        public string diac { get; set; }
    }
}
