//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_services
    {
        public int id { get; set; }
        public Nullable<int> service_id { get; set; }
        public string service_name { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<bool> flage { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public string diag { get; set; }
        public string blood { get; set; }
        public Nullable<System.DateTime> lmp { get; set; }
        public Nullable<System.DateTime> edd { get; set; }
        public string no_follicleRT { get; set; }
        public string no_follicleLT { get; set; }
        public string size_follicleRT { get; set; }
        public string size_follicleLT { get; set; }
        public string endo { get; set; }
        public string otherRT { get; set; }
        public string otherLT { get; set; }
        public string wks { get; set; }
        public string sex { get; set; }
        public string fwt { get; set; }
        public string other { get; set; }
        public string hb { get; set; }
        public string rbs { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<bool> come { get; set; }
        public Nullable<bool> enter { get; set; }
    }
}
