//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_history
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
        public Nullable<int> service_id { get; set; }
        public string service_name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string doc_name { get; set; }
        public Nullable<int> details_id { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> date_now { get; set; }
        public Nullable<bool> check_out { get; set; }
        public Nullable<bool> confirm_calc { get; set; }
        public Nullable<double> hos_value { get; set; }
        public Nullable<double> doc_value { get; set; }
        public string serTypee { get; set; }
        public Nullable<double> main_val { get; set; }
        public Nullable<double> unit_val { get; set; }
    }
}
