//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_micturation
    {
        public int id { get; set; }
        public Nullable<bool> Feeling_uicomplete_En { get; set; }
        public Nullable<bool> post_micturation_drippliz { get; set; }
        public Nullable<int> pat_id { get; set; }
        public Nullable<int> Rec_id { get; set; }
        public string txt { get; set; }
    }
}
