//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session_med
    {
        public int id { get; set; }
        public Nullable<int> Clinic_RecID { get; set; }
        public string TypeService { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string name { get; set; }
        public string extra { get; set; }
        public string note { get; set; }
        public Nullable<int> printFlag { get; set; }
    }
}
