//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        public int id { get; set; }
        public Nullable<bool> kindlyRt { get; set; }
        public Nullable<bool> kindlylt { get; set; }
        public Nullable<bool> UreterRt { get; set; }
        public Nullable<bool> Ureterlt { get; set; }
        public Nullable<bool> BlodderRt { get; set; }
        public Nullable<bool> Blodderlt { get; set; }
        public Nullable<bool> PeuileRt { get; set; }
        public Nullable<bool> Peuilelt { get; set; }
        public Nullable<bool> TestisRt { get; set; }
        public Nullable<bool> Testislt { get; set; }
        public Nullable<bool> scroumRt { get; set; }
        public Nullable<bool> scroumLt { get; set; }
        public Nullable<bool> peqRt { get; set; }
        public Nullable<bool> preLt { get; set; }
        public string others { get; set; }
        public Nullable<int> surg_id { get; set; }
    }
}
