//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream_options
    {
        public int id { get; set; }
        public Nullable<int> StreamId { get; set; }
        public Nullable<bool> slow { get; set; }
        public Nullable<bool> Splithlis { get; set; }
        public Nullable<bool> liten_mitteut { get; set; }
    }
}
