//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_history
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_name { get; set; }
        public string doc_name { get; set; }
        public string assistant_name { get; set; }
        public string Nursery_name { get; set; }
        public string surgeon_name { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<double> surgery_price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string notes { get; set; }
        public string user_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public string otherSurg { get; set; }
        public string operation_description { get; set; }
        public string operation_done { get; set; }
        public string trent { get; set; }
        public string previous_opeation { get; set; }
        public string Drauis { get; set; }
        public string Tubes { get; set; }
        public string stitches { get; set; }
        public string Dressuis { get; set; }
        public string cathers { get; set; }
        public string stuits { get; set; }
        public string Prosthetic { get; set; }
        public string other_instruction { get; set; }
        public Nullable<double> period { get; set; }
        public string Anaestusia { get; set; }
        public string TypeSurg { get; set; }
    }
}
