//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string patient_name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> Rel_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> code { get; set; }
        public string typeticket { get; set; }
        public Nullable<int> doc_id { get; set; }
        public string RelationType { get; set; }
        public string doc_name { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
        public string note { get; set; }
    }
}
