//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<System.DateTime> ex_date { get; set; }
        public Nullable<int> med_id { get; set; }
        public Nullable<int> ticket_id { get; set; }
        public Nullable<int> dep_id { get; set; }
        public Nullable<int> flag { get; set; }
        public string p_name { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<System.DateTime> datenow { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> check_out { get; set; }
        public Nullable<int> ticketId { get; set; }
    }
}
