//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccoHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTS
    {
        public int id { get; set; }
        public Nullable<bool> Mass { get; set; }
        public Nullable<bool> pain { get; set; }
        public Nullable<bool> Heuiaturia { get; set; }
        public Nullable<int> pat_id { get; set; }
        public string pat_name { get; set; }
        public string txt { get; set; }
        public Nullable<int> Rec_id { get; set; }
    }
}
